### ISSUE TITLE
What is the CSV format need to run this project?

### ISSUE THREAD

**Issue by JafferWilson** [EA31337/Birt-CSV2FXT#4]
I have successfully removed few errors but still a confusion is there. What is the format of the input csv file?
I am confused whether to give the ticks or OHLC? Please let me know the format of the header of the CSV. If possible can you share one small file that will help me in testing it please?

**Comment by JafferWilson** [comment]
@kenorb Please let me know what you can tell me regarding this issue?

**Comment by kenorb** [comment]
> I am confused whether to give the ticks or OHLC?

- FXT is tick level data format, so ticks.
- HST is OHLC format.

For the format, have a look at this format: https://github.com/FX-Data/FX-Data-EURUSD-DS/tree/EURUSD-2019/EURUSD/2019/01 (you can download these files as a start).

I would recommend to use `convert_csv_to_mt.py` Python script instead for the conversion (CSV->FXT), you can find it in [FX31337/FX-BT-Scripts](https://github.com/FX31337/FX-BT-Scripts/blob/master/convert_csv_to_mt.py). Since I'm not familiar with Birt's script.

If you're looking for already generated FXT files ready to run on the platform, check [FX-Data repo releases](https://github.com/FX-Data/FX-Data-EURUSD-DS/releases).

**Comment by JafferWilson** [comment]
@kenorb Thank you for your time. I will sure try this.
Is there any other way I can contact you?

**Comment by kenorb** [comment]
> @kenorb Thank you for your time. I will sure try this.
> Is there any other way I can contact you?

Try on Telegram: https://t.me/EA31337.

**Comment by JafferWilson** [comment]
Thank you very much.
